# 插件列表
pluginList: [
  "com.testerhome.appcrawler.plugin.LogPlugin",
  "com.testerhome.appcrawler.plugin.TagLimitPlugin"
]
# 是否截图
saveScreen: true
reportTitle: "课堂-UI遍历"
# 结果目录
resultDir: "/Users/liumingwei/Crawler"
# 在执行操作后等待多少毫秒刷新
waitLoading: 500
waitLaunch: 6000
# 结果报告是否展示没有遍历被取消的控件
showCancel: true
# 最大运行时间
maxTime: 10800
# 默认的最大深度10, 结合baseUrl可很好的控制遍历的范围
maxDepth: 10

# appium的capability通用配置
capability:
  # Appium是否需要自动安装和启动应用。默认值true
  autoLaunch: "true"
  # 直接转换到 WebView 上下文。 默认值 false
  autoWebview: "false"
  # 不要在会话前重置应用状态。默认值false。
  noReset: "true"
  fullReset: "false"
  appium: "http://0.0.0.0:4723/wd/hub"
  deviceName: "ce071717d999471e057e"
  appPackage: "com.xes.jazhanghui.activity"
  appActivity: ".mvp.start.StartActivity"
  # dontStopAppOnReset: true
  automationName: "uiautomator2"
  platformName: "Android"
  #以下为重置手机输入法为 appium 输入法
  unicodeKeyboard: true
  resetKeyboard: true

# 遍历范围设定
selectedList:
  - xpath: "//*[@clickable='true']"
  - xpath: "//android.widget.TextView[@text='课堂']"
    action: "click"

# 优先被遍历
firstList:
  - xpath: "//android.widget.TextView[@text='课堂']"
    action: "click"

# url黑名单，用户排除某些页面
urlBlackList:
  - "//android.widget.TextView[@text='发现']"

# 黑名单列表  匹配风格, 默认排除内容是2个数字以上的控件
blackList:
  - xpath: "//*[contains(@resource-id,'Custom_InfoWindow_Navigate')]"
    action: null
    actions: []
    times: 0
  - xpath: "//*[contains(@text,'我的')]"
    action: null
    actions: []
    times: 0
  - xpath: "//*[contains(@text,'选课')]"
    action: null
    actions: []
    times: 0

  # ------------ 防止跳出课堂页面 -----------
  - xpath: "//*[contains(@resource-id,'id/bottomBar')]"
    action: null
    actions: []
    times: 0
  - xpath: "//*[contains(@resource-id,'id/img_bottom_bar')]"
    action: null
    actions: []
    times: 0
  - xpath: "//android.widget.TextView[@text='发现']"
    action: null
    actions: []
    times: 0
  # ------------ 防止跳出课堂页面 -----------


# 最后应该遍历的元素特征
#lastList:
#  - xpath: "//*[contains(@resource-id,'rv_study')]"
#    action: driver.swipe(0.5, 0.8, 0.5, 0.2)
#    times: 0

triggerActions:
  # 去开启
  - action: "click"
    xpath: "//android.widget.TextView[@text='去开启']"
    times: 0

  # 权限允许
  - action: "click"
    xpath: "//*[contains(@resource-id,'permission_allow_button')]"
    times: 0

  # 系统个性化 确定
  - action: "click"
    xpath: "//*[contains(@resource-id,'button1')]"
    times: 0

  # 协议 同意
  - action: "click"
    xpath: "//android.widget.TextView[@text='同意']"
    times: 0

  # 升级弹框 关闭
  - action: "click"
    xpath: "//*[contains(@resource-id,'version_update_close_img')]"
    times: 3

  # 相机&相册 取消
  - action: "click"
    xpath: "//*[contains(@resource-id,'MapThirdMaps_Cancel')]"
    times: 3

  # 登录流程
  - action: "click"
    xpath: "//android.widget.TextView[@text='密码登录']"
    times: 1
  - action: "15011162592"
    xpath: "//*[contains(@resource-id,'xes_login_username')]"
    times: 1
  - action: "123456Qaz"
    xpath: "//*[contains(@resource-id,'xes_login_password')]"
    times: 1
  - action: "click"
    xpath: "//*[contains(@resource-id,'xes_login_button')]"
    times: 1

 # 关闭趣味电台
  - action: "click"
    xpath: "//*[contains(@resource-id,'iv_player_close')]"
    times: 0

 # 关闭任务答题弹款
  - action: "click"
    xpath: "//*[contains(@resource-id,'iv_dialog_icon_center_close')]"
    times: 0