# 插件列表
pluginList: [
  "com.testerhome.appcrawler.plugin.LogPlugin",
  "com.testerhome.appcrawler.plugin.TagLimitPlugin"
]
# 是否截图
saveScreen: true
#日志级别
logLevel: "TRACE"
#报告名称
reportTitle: "我的页-UI遍历测试报告"
# 结果目录
resultDir: "/Users/test/jenkins/workspace/Xes-My-UiAppCrawler/log"
# 在执行操作后等待多少毫秒刷新
waitLoading: 500
waitLaunch: 6000
# 结果报告是否展示没有遍历被取消的控件
showCancel: true
# 最大运行时间
maxTime: 10800
# 默认的最大深度10, 结合baseUrl可很好的控制遍历的范围
maxDepth: 10

# appium的capability通用配置
capability:
  # Appium是否需要自动安装和启动应用。默认值true
  autoLaunch: "true"
  # 直接转换到 WebView 上下文。 默认值 false
  autoWebview: "false"
  # 不要在会话前重置应用状态。默认值false。
  noReset: "true"
  fullReset: "false"
  appium: "http://0.0.0.0:4723/wd/hub"
  deviceName: "ce071717d999471e057e"
  appPackage: "com.xes.jazhanghui.activity"
  appActivity: ".mvp.start.StartActivity"
  # dontStopAppOnReset: true
  automationName: "uiautomator2"
  platformName: "Android"
  #以下为重置手机输入法为appium输入法
  unicodeKeyboard: true
  resetKeyboard: true

# 遍历范围设定
selectedList:
  - xpath: "//*[@clickable='true']"
  - xpath: "//android.widget.TextView[@text='我的']"

# 优先被遍历
firstList:
  - xpath: "//android.widget.TextView[@text='我的']"

# 黑名单列表  匹配风格, 默认排除内容是2个数字以上的控件
blackList:

  # 屏蔽 报错控件
  - xpath: "//*[contains(@class,'android.support.v7.app.ActionBar$Tab')]"
    action: null
    times: 0

  # 屏蔽 导航 防止跳出应用
  - xpath: "//*[contains(@resource-id,'Custom_InfoWindow_Navigate')]"
    action: null
    times: 0

  # 屏蔽 删除学员 防止误删
  - xpath: "//*[contains(@resource-id,'img_swipe_delete')]"
    action: null
    times: 0

  # 屏蔽 去关注 防止跳出应用
  - xpath: "//*[contains(@resource-id,'bg_img')]"
    action: null
    times: 0

  # 屏蔽 分享 防止跳出应用
  - xpath: "//*[contains(@resource-id,'menu_share')]"
    action: null
    times: 0

  # 屏蔽 口算拍照 防止跳出应用
  - xpath: "//*[contains(@resource-id,'MapThirdMaps_Cancel')]"
    action: null
    times: 0

  # 关闭应用
  - xpath: "//*[contains(@resource-id,'aerr_close')]"
    action: click
    times: 0

# 制定规则（action、xpath、times）
triggerActions:
  # 去开启
  - action: "click"
    xpath: "//android.widget.TextView[@text='去开启']"
    times: 0

  # 权限允许
  - action: "click"
    xpath: "//*[contains(@resource-id,'permission_allow_button')]"
    times: 0

  # 三星手机系统个性化 确定
  - action: "click"
    xpath: "//*[contains(@resource-id,'button1')]"
    times: 0

  # 协议 同意
  - action: "click"
    xpath: "//android.widget.TextView[@text='同意']"
    times: 0

  # 关闭趣味电台
  - action: "click"
    xpath: "//*[contains(@resource-id,'iv_player_close')]"
    times: 0

 # 相机&相册 取消
  - action: "click"
    xpath: "//*[contains(@resource-id,'xes_cancel')]"
    times: 0

# # 弹框 取消
#  - action: "click"
#    xpath: "//*[contains(@resource-id,'btn_commondialog_neg')]"
#    times: 0

 # 相机&相册 取消
  - xpath: "//*[contains(@resource-id,'tv_cancle_media_action')]"
    action: click
    times: 0

 # 关闭应用
  - xpath: "//*[contains(@resource-id,'aerr_close')]"
    action: click
    times: 0

 # 登录流程
  - action: "click"
    xpath: "//android.widget.TextView[@text='密码登录']"
    times: 0
  - action: "15011162592"
    xpath: "//*[contains(@resource-id,'xes_login_username')]"
    times: 0
  - action: "123456Qaz"
    xpath: "//*[contains(@resource-id,'xes_login_password')]"
    times: 0
  - action: "click"
    xpath: "//*[contains(@resource-id,'xes_login_button')]"
    times: 0